

services:

  db:
    image: postgres:15.3
    container_name: wallet_db
    environment:
      POSTGRES_DB: wallet
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345678
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "user"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["postgres", "-c", "listen_addresses=*"]

  app:
    image: wallet-app
    build:
      context: .
      args:
        - BUILDKIT_INLINE_CACHE=1
      dockerfile: Dockerfile
    container_name: wallet_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wallet
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 12345678
      SPRING_LIQUIBASE_ENABLED: "true"
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:/db/changelog-master.yaml
      SPRING_DATASOURCE_HIKARI_MAXIMUM-POOL-SIZE: 15
      JAVA_OPTS: "-XX:MaxRAMPercentage=75"
    healthcheck:
        test: [ "CMD-SHELL", "curl -f http://localhost:8070/actuator/health || exit 1" ]
        interval: 10s
        timeout: 10s
        retries: 10
        start_period: 40s
    ports:
      - "8070:8070"
volumes:
  postgres_data:
    driver: local
